version: "3"

services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    environment:
      - TZ=Asia/Seoul
    ports:
      - 6379:6379
    volumes:
      - ./conf:/usr/local/conf
      - ./data:/data
    command: /usr/local/bin/redis-server /usr/local/conf/redis.conf

networks:
  default:
    name: redis_net
    external: true
      